sudo: required
dist: trusty

language: php
php:
  - 5.5
  - 5.6
  - 7.0
env:
  - TEST_SUITE=unit
  - TEST_SUITE=integration_part_1
  - TEST_SUITE=integration_part_2
  - TEST_SUITE=integration_integrity
  - TEST_SUITE=static_phpcs
  - TEST_SUITE=static_annotation
cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/bin
matrix:
  exclude:
    - php: 5.6
      env: TEST_SUITE=static_phpcs
    - php: 5.6
      env: TEST_SUITE=static_annotation
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix
  - sh -c 'if [ "$CASHER_DIR" ]; then
         if [ -x $HOME/.cache/bin/composer ]; then
           $HOME/.cache/bin/composer self-update; echo '';
         else
           mkdir -p $HOME/.cache/bin;
           curl --connect-timeout 30 -sS https://getcomposer.org/installer
           | php -- --install-dir $HOME/.cache/bin/ --filename composer;
         fi
       fi'
  - export PATH="$HOME/.cache/bin:$PATH"
before_script:
  # Mock mail
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
  - echo 'sendmail_path = "/usr/sbin/sendmail -t -i "' > $(php --ini|grep -m 1 "ini files in:"|cut -d ":" -f 2)/sendmail.ini
  # Disable xDebug
  - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  # Install MySQL 5.6, create DB for integration tests
  - >
      sh -c "if [ '$TEST_SUITE' = 'integration_part_1' ] || [ '$TEST_SUITE' = 'integration_part_2' ] || [ '$TEST_SUITE' = 'integration_integrity' ]; then
      sudo apt-get remove -y -qq --purge mysql-common mysql-server-5.5 mysql-server-core-5.5 mysql-client-5.5 mysql-client-core-5.5;
      sudo apt-get -y -qq autoremove;
      sudo apt-get -y -qq autoclean;
      sudo apt-get install -y -qq mysql-server-5.6 mysql-client-5.6;
      fi"
  # Change memory_limit for travis
  - echo 'memory_limit = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv rehash;
  - composer install --no-interaction --prefer-dist
script:
  - sh -c "./vendor/bin/phing $TEST_SUITE"
