sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - postfix
language: php
php:
  - 5.6
  - 7.0
env:
  global:
    - COMPOSER_BIN_DIR=~/bin
    - INTEGRATION_SETS=3
  matrix:
    - TEST_SUITE=unit
    - TEST_SUITE=integration INTEGRATION_INDEX=1
    - TEST_SUITE=integration INTEGRATION_INDEX=2
    - TEST_SUITE=integration INTEGRATION_INDEX=3
    - TEST_SUITE=static
cache:
  apt: true
  directories: $HOME/.composer/cache
matrix:
  exclude:
    - php: 7.0
      env: TEST_SUITE=static
before_install: ./dev/travis/before_install.sh
install: composer install --no-interaction --prefer-dist
before_script: ./dev/travis/before_script.sh
script:
  - phpcs --version
  - ./vendor/bin/phpcs --version
  - cd dev/tests/$TEST_SUITE
  - test $TEST_SUITE = "static" && TEST_FILTER='--filter "Magento\\Test\\Php\\LiveCodeTest"' || true
  - phpunit $TEST_FILTER
